name: Dog API Test Automation CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Executa testes todos os dias às 9h UTC
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Validate Maven project
        run: mvn validate

      - name: Compile project
        run: mvn compile

      - name: Run tests
        run: mvn clean test
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: Generate Allure Report
        run: mvn allure:report
        if: always()

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 30

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 30

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
          retention-days: 30

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  smoke-tests:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Smoke Tests
        run: |
          if [ -f "./scripts/run-tests.sh" ]; then
            chmod +x ./scripts/run-tests.sh
            ./scripts/run-tests.sh smoke
          else
            mvn clean test -Dcucumber.filter.tags="@smoke"
          fi
        env:
          MAVEN_OPTS: "-Xmx1024m"

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check
        continue-on-error: true

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: owasp-report
          path: target/dependency-check-report.html
          retention-days: 30

  deploy-reports:
    runs-on: ubuntu-latest
    needs: [test, smoke-tests]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: reports

  notify:
    runs-on: ubuntu-latest
    needs: [test, smoke-tests, security-scan, deploy-reports]
    if: always()
    
    steps:
      - name: Notify on Success
        if: ${{ needs.test.result == 'success' && needs.smoke-tests.result == 'success' }}
        run: |
          echo "✅ All tests passed successfully!"
          echo "📊 Reports available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/reports"

      - name: Notify on Failure
        if: ${{ needs.test.result == 'failure' || needs.smoke-tests.result == 'failure' }}
        run: |
          echo "❌ Tests failed!"
          echo "Check the workflow logs for details"
          exit 1